### ISSUE TITLE
more can do with Ckeditor

### ISSUE THREAD

**Issue by deciia** [MomoPZ/brackets-ckeditor#2]
Whether the page can be edited directly or Real-time editing with Ckeditor, and then return to the source of it?

**Comment by MomoPZ** [comment]
Hi deciia,
the extension does not support real-time editing. You can edit/insert html and return to source. It's just a helper for easy pasting content from other sources into your html.
For other features use Live Preview etc. in Brackets...
Regards, 
Momo
