### ISSUE TITLE
1.02 version, the brackets-ckeditor icon can not be displayed

### ISSUE THREAD

**Issue by deciia** [MomoPZ/brackets-ckeditor#3]
After the update to 1.02, I can not use it in the new version of Brackets.

**Comment by MomoPZ** [comment]
Did you download CKeditor and extract it into the brackets-ckeditor extension-folder?
After upgrading you have to do that again!

**Comment by deciia** [comment]
yes,i have done it.with 1.01 version,it can work,but for 1.02 ,it won't work,the icon cann't display.

------------------ 原始邮件 ------------------
发件人: "Momo";notifications@github.com;
发送时间: 2014年5月21日(星期三) 下午5:10
收件人: "MomoPZ/brackets-ckeditor"brackets-ckeditor@noreply.github.com; 
抄送: "断水"deciia@qq.com; 
主题: Re: [brackets-ckeditor] 1.02 version, the brackets-ckeditor icon cannot be displayed (#3)

Did you download CKeditor and extract it into the brackets-ckeditor extension-folder?
 After upgrading you have to do that again!

**Comment by MomoPZ** [comment]
Please reload Brackets (F5). Then press F12 to debug in Chrome. Filter the debug messages in Chrome by selecting the error-tab. Send me the errors you get.

**Comment by deciia** [comment]
Failed to load resource file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/brackets-ckeditor/ckeditor/ckeditor.js

[Extension] failed to load C:/Users/danping/AppData/Roaming/Brackets/extensions/user/brackets-ckeditor Error: Script error for: ckeditor/ckeditor http://requirejs.org/docs/errors.html#scripterror /utils/ExtensionLoader.js:209

getPreferenceStorage is called with client ID 'me.drewh.jsbeautify-autosave,' use PreferencesManager.definePreference instead.     at Object.getPreferenceStorage (/preferences/PreferencesManager.js:126:32)     at Object.<anonymous> (file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/brackets-beautify/main.js:253:42)     at Object.context.execCb (file:///D:/Program%20Files%20(x86) /utils/DeprecationWarning.js:85
getValue is called to get preference 'enabled,' use PreferencesManager.get instead.     at PreferenceStorage.getValue (/preferences/PreferenceStorage.js:128:28)     at Object.<anonymous> (file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/brackets-beautify/main.js:257:31)     at Object.context.execCb (file:///D:/Program%20Files%20(x86) /utils/DeprecationWarning.js:85
setValue is called to set preference 'enabled,' use PreferencesManager.set instead.     at PreferenceStorage.setValue (/preferences/PreferenceStorage.js:115:28)     at toggle (file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/brackets-beautify/main.js:249:21)     at Object.<anonymous> (file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/brackets-beautify/main.js:283:5)     at Object.context.execCb (file:///D:/Program%20Files%20(x86) /utils/DeprecationWarning.js:85
Deprecated: resizable panels should be created via PanelManager.createBottomPanel(). Using Resizer directly will stop working in the future.  Element: 
<div id=​"editor-console" class=​"collapsible" style=​"box-sizing:​ border-box;​ display:​ none;​">​…​</div>​
 /utils/Resizer.js:182

[Extension] failed to load C:/Users/danping/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git Error: Preference brackets-git.stripWhitespaceFromCommits was redefined main.js:87

Error: Preference brackets-git.stripWhitespaceFromCommits was redefined     at PreferencesSystem._.extend.definePreference (/preferences/PreferencesBase.js:1113:23)     at Object.PrefixedPreferencesSystem.definePreference (/preferences/PreferencesBase.js:891:30)     at file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Preferences.js:48:19     at y (/thirdparty/lodash.js:9:73)     at Function.Ot (/thirdparty/lodash.js:21:195)     at Object.<anonymous> (file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Preferences.js:44:7)     at Object.context.execCb (file:///D:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1635:33)     at Object.Module.check (file:///D:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:866:55)     at Object.Module.enable (file:///D:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1142:22)     at Object.Module.init (file:///D:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:779:26) main.js:80
Uncaught RangeError: Maximum call stack size exceeded require.js:1
2Uncaught RangeError: Maximum call stack size exceeded require.js:1154
Uncaught RangeError: Maximum call stack size exceeded require.js:1154

Warning: FileIndexManager is deprecated. Use ProjectManager.getAllFiles() instead main.js:87

console.errormain.js:87

Unhandled exception in getAllFiles handler:  
TypeError

 /project/ProjectManager.js:2076

------------------ 原始邮件 ------------------
发件人: "Momo"notifications@github.com; 
发送时间: 2014年5月21日(星期三) 下午5:36
收件人: "MomoPZ/brackets-ckeditor"brackets-ckeditor@noreply.github.com; 
抄送: "断水"deciia@qq.com; 
主题: Re: [brackets-ckeditor] 1.02 version, the brackets-ckeditor icon cannot be displayed (#3)

Please reload Brackets (F5). Then press F12 to debug in Chrome. Filter the debug messages in Chrome by selecting the error-tab. Send me the errors you get.

&mdash;

**Comment by MomoPZ** [comment]
The extension can't find ckeditor:
<i>Failed to load resource file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/brackets-ckeditor/ckeditor/ckeditor.js</i>
So you didn't download and extract ckeditor to the extension folder. Please do that and it will work. 
(You can check that by: Brackets -> Help -> Show Extension folder -> Browse to user/brackets-ckeditor. There should be the folder "ckeditor".)
Regards
Momo

**Comment by deciia** [comment]
i see ,i wii try it.

------------------ 原始邮件 ------------------
发件人: "Momo"notifications@github.com; 
发送时间: 2014年5月21日(星期三) 晚上6:20
收件人: "MomoPZ/brackets-ckeditor"brackets-ckeditor@noreply.github.com; 
抄送: "断水"deciia@qq.com; 
主题: Re: [brackets-ckeditor] 1.02 version, the brackets-ckeditor icon cannot be displayed (#3)

The extension can't find ckeditor:
Failed to load resource file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/brackets-ckeditor/ckeditor/ckeditor.js
 So you didn't download and extract ckeditor to the extension folder. Please do that and it will work. 
 (You can check that by: Brackets -> Help -> Show Extension folder -> Browse to user/brackets-ckeditor. There should be the folder "ckeditor".)
 Regards
 Momo

&mdash;

**Comment by deciia** [comment]
when i choose a close tag and click the icon,the openning editor look like the following image:

the first line's source:

<p>div id=&quot;content&quot;&gt; </p>

------------------ 原始邮件 ------------------
发件人: "Momo"notifications@github.com; 
发送时间: 2014年5月21日(星期三) 晚上6:20
收件人: "MomoPZ/brackets-ckeditor"brackets-ckeditor@noreply.github.com; 
抄送: "断水"deciia@qq.com; 
主题: Re: [brackets-ckeditor] 1.02 version, the brackets-ckeditor icon cannot be displayed (#3)

The extension can't find ckeditor:
Failed to load resource file:///C:/Users/danping/AppData/Roaming/Brackets/extensions/user/brackets-ckeditor/ckeditor/ckeditor.js
 So you didn't download and extract ckeditor to the extension folder. Please do that and it will work. 
 (You can check that by: Brackets -> Help -> Show Extension folder -> Browse to user/brackets-ckeditor. There should be the folder "ckeditor".)
 Regards
 Momo

&mdash;

**Comment by MomoPZ** [comment]
You are at Bracket's release 39? 
Yeah, I know. See issue #4 . Sorry for that!
I'm working on it! Update will come soon! 
Regards Momo

PS: Now you know how to update, right? ;-)

**Comment by deciia** [comment]
ok,thanks for help.

------------------ 原始邮件 ------------------
发件人: "Momo"notifications@github.com; 
发送时间: 2014年5月21日(星期三) 晚上6:48
收件人: "MomoPZ/brackets-ckeditor"brackets-ckeditor@noreply.github.com; 
抄送: "断水"deciia@qq.com; 
主题: Re: [brackets-ckeditor] 1.02 version, the brackets-ckeditor icon cannot be displayed (#3)

You are at Bracket's release 39? 
 Yeah, I know. See issue #4 . Sorry for that!
 I'm working on it! Update will come soon! 
 Regards Momo

PS: Now you know hot to update, right? ;-)

&mdash;
