### ISSUE TITLE
Not clear install instraction

### ISSUE THREAD

**Issue by VitaliyAT** [MomoPZ/brackets-ckeditor#6]
_Download CKeditor and extract it into the brackets-ckeditor extension-folder (don't rename folder containing CKEditor, name must remain ckeditor)_
Finaly what name of folder should be **brackets-ckeditor** or **ckeditor** ?
How structure showld be look like?

```
ExtFolder
|->brackets-ckeditor
   |->adapters
   |->lang
   |->...etc.
```

**Comment by MomoPZ** [comment]
Just put the extracted folder of ckeditor into the bracket-ckeditor-extension folder:
`ExtFolder`
`|->brackets-ckeditor`
`--|->**ckeditor**`

**Comment by VitaliyAT** [comment]
Not clear again. Lets I tell what I do:
1) Download CKeditor (_**ckeditor_4.5.10_standard.zip**_)
in this archive I see one folder _**cheditor**_
2) _**Brackets->Extension Manger->CKEditor for Brackets->install**_ : got errors (according instructions it's ok)
3) _**Brackets->Help->Extension folder**_
(C:\Users\{username}\AppData\Roaming\Brackets\extensions)
In this folder I see folders named _**disabled**_ and _**user**_
If I placed it here and restart Brackets as You told - nothing happened.
If I go to folder  _**user**_ (C:\Users\В\AppData\Roaming\Brackets\extensions\user) (And nowhere clear info about it.) I see folder _**brackets-ckeditor**_ only if I put folder  _**cheditor**_ in it - it start working.
Other words normal instruction should have few words: 
"Put folder "_**cheditor**_" from archive to %AppData%\Roaming\Brackets\extensions\user\brackets-ckeditor" and it will be clear for everybody.
